openapi: 3.0.1
info:
  title: foobar-foo
  description: Import from "foobar-foo" Function App
  version: '1.0'
servers:
  - url: https://foobar-apim-service.azure-api.net/foobar-foo
paths:
  /foo:
    post:
      summary: template
      operationId: template
      responses:
        '200':
          description: 
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]