openapi: 3.0.1
info:
  title: Chuck Norris API
  description: This is the OpenAPI documentation on the chuck norris API. This API was built in the cloud engineering bootcamp in Azure. A large reason why API documentation is important is to increase API adoption. Comprehensive documentation on all of the functionality, how to effectively use and integrate, and updates on the API lifecycle improves the experience for those using your APIs. Could you use an API without documentation? Sure, it’s technically possible. But you can grasp the API’s technical content and integration instructions much better with complete and accurate documentation. API documentation is important in your lifecycle. But do you know everything there is to know about the lifecycle? Explore our hub and become an expert today. 
  version: '0.1'
servers:
  - url: http://chuck-azure-demo-1.azurewebsites.net/api
paths:
  /JokeCategories:
    get:
      description: Returns all possible joke categories.
      responses:
        '200':
          description: An example of a successful GET call.
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                'Retrieve Categories':
                  value: >-
                    ["animal","career","celebrity","dev","explicit","fashion","food","history","money","movie","music","political","religion","science","sport","travel"]
      servers:
        - url: http://chuck-azure-demo-1.azurewebsites.net/api
    servers:
      - url: http://chuck-azure-demo-1.azurewebsites.net/api
  /RandomJoke:
    get:
      description: Returns a random chuck norris joke retrieved from the chuck-norris.io API. This API ensures that no offensive jokes are sent.
      responses:
        '200':
          description: An example of a successful GET call.
          content:
            application/json:
              schema:
                type: object
                properties:
                  icon_url:
                    type: string
                  updated_at:
                    type: string
                  created_at:
                    type: string
                  categories:
                    type: array
                    items:
                      type: string
                  id:
                    type: string
                  value:
                    type: string
                  url:
                    type: string
              examples:
                'RandomJoke':
                  value: >-
                    {"categories":[],"created_at":"2020-01-05
                    13:42:28.143137","icon_url":"https://assets.chucknorris.host/img/avatar/chuck-norris.png","id":"A6uXg0uJTjW74_qfyCm-Ww","updated_at":"2020-01-05
                    13:42:28.143137","url":"https://api.chucknorris.io/jokes/A6uXg0uJTjW74_qfyCm-Ww","value":"Roundhoused
                    kicked by Chuck Norris... Life ruined forever."}
      servers:
        - url: http://chuck-azure-demo-1.azurewebsites.net/api
    servers:
      - url: http://chuck-azure-demo-1.azurewebsites.net/api