swagger: '2.0'
info:
  title: API Config
  description: API Config
  version: 1.0.0
schemes:
- https
produces:
- application/json
paths:
  /init:
    get:
      summary: Setup database or MVCC-DB
      operationId: /init
      x-google-backend:
        address: https://europe-west1-master-thesis-faas-monad.cloudfunctions.net/sqldb-init
      responses:
        '200':
          description: TODO
          schema:
            type: string
  /send:
    get:
      summary: Make a transaction
      operationId: /send
      x-google-backend:
        address: https://europe-west1-master-thesis-faas-monad.cloudfunctions.net/worker
      responses:
        '200':
          description: TODO
          schema:
            type: string
  /status:
    get:
      summary: Get the current state of an account
      operationId: /status
      x-google-backend:
        address: https://europe-west1-master-thesis-faas-monad.cloudfunctions.net/sqldb-get
      responses:
        '200':
          description: TODO
          schema:
            type: string
