swagger: '2.0'
info:
  title: API Config
  description: API Config
  version: 1.0.0
schemes:
- https
produces:
- application/json
paths:
  /foo:
    get:
      summary: lambda for foo
      operationId: /foo
      x-google-backend:
        address: https://europe-west1-master-thesis-faas-monad.cloudfunctions.net/foobar-foo
      responses:
        '200':
          description: TODO
          schema:
            type: string
  /bar:
    get:
      summary: lambda for bar
      operationId: /bar
      x-google-backend:
        address: https://europe-west1-master-thesis-faas-monad.cloudfunctions.net/foobar-bar
      responses:
        '200':
          description: TODO
          schema:
            type: string
